//STUDENTS
export const GET_STUDENTS = 'GET_STUDENTS';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
//COHORTS
export const GET_COHORTS = 'GET_COHORTS';
export const CREATE_COHORT = 'CREATE_COHORT';
export const UPDATE_COHORT = 'UPDATE_COHORT';
//USERS
export const GET_USER = "GET_USER";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
//PROJECTS
export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";