export const GET_STUDENTS = 'GET_STUDENTS';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const GET_COHORTS = 'GET_COHORTS';
export const UPDATE_COHORT = 'UPDATE_COHORT';
